package explotatucerebro;

import explotatucerebro.Interface;
import java.awt.Color;


public class GUICategorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public GUICategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        anatomia = new javax.swing.JButton();
        ciencia = new javax.swing.JButton();
        geografia = new javax.swing.JButton();
        historia = new javax.swing.JButton();
        deportes = new javax.swing.JButton();
        DEPORTE = new javax.swing.JLabel();
        CIENCIA = new javax.swing.JLabel();
        HISTORIA = new javax.swing.JLabel();
        GEOGRAFIA = new javax.swing.JLabel();
        ANATOMIA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CATEGORIAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 5, 400, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("CATEGORIAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 400, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 450, 60));

        anatomia.setBackground(new java.awt.Color(255, 51, 51));
        anatomia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/anatomia.png"))); // NOI18N
        anatomia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        anatomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anatomiaActionPerformed(evt);
            }
        });
        jPanel1.add(anatomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 120, 120));
        anatomia.getAccessibleContext().setAccessibleName("anatomia");

        ciencia.setBackground(new java.awt.Color(51, 153, 0));
        ciencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/ciencia.jpg"))); // NOI18N
        ciencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        ciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cienciaActionPerformed(evt);
            }
        });
        jPanel1.add(ciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, 110));

        geografia.setBackground(new java.awt.Color(0, 153, 255));
        geografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/geografia.jpg"))); // NOI18N
        geografia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        geografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geografiaActionPerformed(evt);
            }
        });
        jPanel1.add(geografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 110, 110));

        historia.setBackground(new java.awt.Color(204, 255, 0));
        historia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/historia.jpg"))); // NOI18N
        historia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaActionPerformed(evt);
            }
        });
        jPanel1.add(historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 110, 110));

        deportes.setBackground(new java.awt.Color(255, 153, 0));
        deportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/deporte.png"))); // NOI18N
        deportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        deportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deportesActionPerformed(evt);
            }
        });
        jPanel1.add(deportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 120, 80, 120));

        DEPORTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DEPORTE.setForeground(new java.awt.Color(255, 153, 0));
        DEPORTE.setText("DEPORTE");
        jPanel1.add(DEPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        CIENCIA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CIENCIA.setForeground(new java.awt.Color(51, 153, 0));
        CIENCIA.setText("CIENCIA");
        jPanel1.add(CIENCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        HISTORIA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HISTORIA.setForeground(new java.awt.Color(255, 255, 51));
        HISTORIA.setText("HISTORIA");
        jPanel1.add(HISTORIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        GEOGRAFIA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GEOGRAFIA.setForeground(new java.awt.Color(0, 153, 204));
        GEOGRAFIA.setText("GEOGRAFIA");
        jPanel1.add(GEOGRAFIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        ANATOMIA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANATOMIA.setForeground(new java.awt.Color(255, 51, 51));
        ANATOMIA.setText("ANATOMIA");
        jPanel1.add(ANATOMIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecciona una categoría");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anatomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anatomiaActionPerformed
        String categoriaSeleccionada = "Anatomia";
        Interface guiInterface = new Interface(categoriaSeleccionada);
        guiInterface.setPanelColor(new Color(255, 51, 51));
        guiInterface.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_anatomiaActionPerformed

    private void geografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geografiaActionPerformed
        String categoriaSeleccionada = "Geografia";
        Interface guiInterface = new Interface(categoriaSeleccionada);
        guiInterface.setPanelColor(new Color(0, 153, 204));
        guiInterface.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_geografiaActionPerformed

    private void deportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deportesActionPerformed
        String categoriaSeleccionada = "Deporte";
        Interface guiInterface = new Interface(categoriaSeleccionada);
        guiInterface.setPanelColor(new Color(255, 153, 0));
        guiInterface.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_deportesActionPerformed

    private void cienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cienciaActionPerformed
        String categoriaSeleccionada = "Ciencias Naturales";
        Interface guiInterface = new Interface(categoriaSeleccionada);
        guiInterface.setPanelColor(new Color(51, 153, 0));
        guiInterface.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_cienciaActionPerformed

    private void historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaActionPerformed
        String categoriaSeleccionada = "Historia";
        Interface guiInterface = new Interface(categoriaSeleccionada);
        guiInterface.setPanelColor(new Color(255, 255, 51));
        guiInterface.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_historiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ProyectoJuego_Conexion.conectar();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANATOMIA;
    private javax.swing.JLabel CIENCIA;
    private javax.swing.JLabel DEPORTE;
    private javax.swing.JLabel GEOGRAFIA;
    private javax.swing.JLabel HISTORIA;
    private javax.swing.JButton anatomia;
    private javax.swing.JButton ciencia;
    private javax.swing.JButton deportes;
    private javax.swing.JButton geografia;
    private javax.swing.JButton historia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
