package explotatucerebro;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @see <a href="https://github.com/Esguvi/ExplotaTuCerebro">GitHub</a> 
 * @author Grupo 1 - Miriam Daimiel Acedo | Víctor Escaso Gutiérrez | Guillermo Lucio García | Alejandro Muñoz Pardo | Carlos Isaac Muriel Cuevas.
*/

public class GUICategorias extends javax.swing.JFrame {
    private String nombreUsuario;
    private static boolean cienciaResuelta = false;
    private static boolean historiaResuelta = false;
    private static boolean anatomiaResuelta = false;
    private static boolean deportesResuelta = false;
    private static boolean geografiaResuelta = false;
    private static int quesosMaximos = 1;
    
    /**
     * Creates new form Categorias
     * @param nombreUsuario
     */
    public GUICategorias(String nombreUsuario, int quesos) {
        if(quesos >= quesosMaximos){
            GUIGanador ganador;
            try {
                ganador = new GUIGanador(nombreUsuario);
                ganador.setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
            dispose();
        }else{
            this.nombreUsuario = nombreUsuario;
            initComponents();
            lblUsuario.setText("Usuario registrado como: " + nombreUsuario);
            lblQuesos.setText("Quesos obtenidos: " + quesos+"/5");
            btnCiencia.setEnabled(!cienciaResuelta);
            btnHistoria.setEnabled(!historiaResuelta);
            btnDeportes.setEnabled(!deportesResuelta);
            btnAnatomia.setEnabled(!anatomiaResuelta);
            btnGeografia.setEnabled(!geografiaResuelta); 
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCategorias = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSombra = new javax.swing.JLabel();
        btnAnatomia = new javax.swing.JButton();
        btnCiencia = new javax.swing.JButton();
        btnGeografia = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnDeportes = new javax.swing.JButton();
        lblDeportes = new javax.swing.JLabel();
        lblCiencia = new javax.swing.JLabel();
        lblHistoria = new javax.swing.JLabel();
        lblGeografia = new javax.swing.JLabel();
        lblAnatomia = new javax.swing.JLabel();
        lblSelecciona = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblQuesos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelCategorias.setBackground(new java.awt.Color(0, 0, 0));
        panelCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(255, 102, 0));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CATEGORIAS");
        panelTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 5, 400, 40));

        lblSombra.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblSombra.setText("CATEGORIAS");
        panelTitulo.add(lblSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 400, 40));

        panelCategorias.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 450, 60));

        btnAnatomia.setBackground(new java.awt.Color(255, 51, 51));
        btnAnatomia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/anatomia.png"))); // NOI18N
        btnAnatomia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btnAnatomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnatomiaActionPerformed(evt);
            }
        });
        panelCategorias.add(btnAnatomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 120, 120));
        btnAnatomia.getAccessibleContext().setAccessibleName("anatomia");

        btnCiencia.setBackground(new java.awt.Color(51, 153, 0));
        btnCiencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/ciencia.jpg"))); // NOI18N
        btnCiencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        btnCiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienciaActionPerformed(evt);
            }
        });
        panelCategorias.add(btnCiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 120));

        btnGeografia.setBackground(new java.awt.Color(0, 153, 255));
        btnGeografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/geografia.jpg"))); // NOI18N
        btnGeografia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        btnGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeografiaActionPerformed(evt);
            }
        });
        panelCategorias.add(btnGeografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 110, 120));

        btnHistoria.setBackground(new java.awt.Color(204, 255, 0));
        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/historia.jpg"))); // NOI18N
        btnHistoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        panelCategorias.add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 110, 120));

        btnDeportes.setBackground(new java.awt.Color(255, 153, 0));
        btnDeportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/deporte.png"))); // NOI18N
        btnDeportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeportesActionPerformed(evt);
            }
        });
        panelCategorias.add(btnDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 120));

        lblDeportes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDeportes.setForeground(new java.awt.Color(255, 153, 0));
        lblDeportes.setText("DEPORTE");
        panelCategorias.add(lblDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        lblCiencia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCiencia.setForeground(new java.awt.Color(51, 153, 0));
        lblCiencia.setText("CIENCIA");
        panelCategorias.add(lblCiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lblHistoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHistoria.setForeground(new java.awt.Color(255, 255, 51));
        lblHistoria.setText("HISTORIA");
        panelCategorias.add(lblHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lblGeografia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGeografia.setForeground(new java.awt.Color(0, 153, 204));
        lblGeografia.setText("GEOGRAFÍA");
        panelCategorias.add(lblGeografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        lblAnatomia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAnatomia.setForeground(new java.awt.Color(255, 51, 51));
        lblAnatomia.setText("ANATOMÍA");
        panelCategorias.add(lblAnatomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        lblSelecciona.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSelecciona.setForeground(new java.awt.Color(255, 255, 255));
        lblSelecciona.setText("Selecciona una categoría");
        panelCategorias.add(lblSelecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/usericon.png"))); // NOI18N
        lblUsuario.setText("jLabel5");
        panelCategorias.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 390, 40));

        btnCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explotatucerebro/img/logouticon.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        panelCategorias.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 160, -1));

        lblQuesos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuesos.setForeground(new java.awt.Color(255, 255, 255));
        lblQuesos.setText("Quesos Obtenidos: 0/5");
        panelCategorias.add(lblQuesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnatomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnatomiaActionPerformed
        String categoriaSeleccionada = "Anatomia";
        Interface guiInterface = new Interface(categoriaSeleccionada, nombreUsuario);
        guiInterface.setPanelColor(new Color(255, 51, 51));
        guiInterface.setVisible(true);
        anatomiaResuelta = true;
        this.dispose(); 
    }//GEN-LAST:event_btnAnatomiaActionPerformed

    private void btnGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeografiaActionPerformed
        String categoriaSeleccionada = "Geografia";
        Interface guiInterface = new Interface(categoriaSeleccionada, nombreUsuario);
        guiInterface.setPanelColor(new Color(0, 153, 204));
        guiInterface.setVisible(true);
        geografiaResuelta = true;
        this.dispose(); 
    }//GEN-LAST:event_btnGeografiaActionPerformed

    private void btnDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeportesActionPerformed
        String categoriaSeleccionada = "Deporte";
        Interface guiInterface = new Interface(categoriaSeleccionada, nombreUsuario);
        guiInterface.setPanelColor(new Color(255, 153, 0));
        guiInterface.setVisible(true);
        deportesResuelta = true;
        this.dispose(); 
    }//GEN-LAST:event_btnDeportesActionPerformed

    private void btnCienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienciaActionPerformed
        String categoriaSeleccionada = "Ciencias Naturales";
        Interface guiInterface = new Interface(categoriaSeleccionada, nombreUsuario);
        guiInterface.setPanelColor(new Color(51, 153, 0));
        guiInterface.setVisible(true);
        cienciaResuelta = true;
        this.dispose(); 
    }//GEN-LAST:event_btnCienciaActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        String categoriaSeleccionada = "Historia";
        Interface guiInterface = new Interface(categoriaSeleccionada, nombreUsuario);
        guiInterface.setPanelColor(new Color(255, 255, 51));
        guiInterface.setVisible(true);
        historiaResuelta = true;
        this.dispose(); 
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        ProyectoJuego_Conexion.conectar();
        GUI gui;
        try {
            gui = new GUI();
            gui.setVisible(true);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ProyectoJuego_Conexion.conectar();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUICategorias(null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnatomia;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCiencia;
    private javax.swing.JButton btnDeportes;
    private javax.swing.JButton btnGeografia;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JLabel lblAnatomia;
    private javax.swing.JLabel lblCiencia;
    private javax.swing.JLabel lblDeportes;
    private javax.swing.JLabel lblGeografia;
    private javax.swing.JLabel lblHistoria;
    private javax.swing.JLabel lblQuesos;
    private javax.swing.JLabel lblSelecciona;
    private javax.swing.JLabel lblSombra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
